import { Header } from "@/components/Header";
import * as S from "../styles/homeStyles";

import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Cryptotech | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Header />

      <S.HomeContainer></S.HomeContainer>
    </>
  );
}
